# Generated by Django 4.2.7 on 2026-06-29 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_quiz_question_discussion_quizattempt_lessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='lesson',
        ),
        migrations.AddField(
            model_name='discussion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='courses.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='duration',
            field=models.FloatField(default=0.0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='section',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='section_thumbnails/'),
        ),
        migrations.AddField(
            model_name='section',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='section_videos/'),
        ),
        migrations.AddField(
            model_name='section',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.section'),
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sectionprogress',
            unique_together={('student', 'section')},
        ),
    ]
